name: Deno Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Verify Deno installation
        run: deno --version

      - name: Run tests
        run: deno test

      - name: Run linter
        run: deno lint

      - name: Check formatting
        run: deno fmt --check
